export enum OfferConstants {
  nameMinLength = 10,
  nameMaxLength = 100,
  descMinLength = 20,
  descMaxLength = 1024,
  ratingMin = 1,
  ratingMax = 5,
  bedroomsMin = 1,
  bedroomsMax = 8,
  adultsMin = 1,
  adultsMax = 10,
  priceMin = 100,
  priceMax = 100000,
  offerTypeMin = 3,
  offerTypeMax = 10,
  imageArraySize = 6,
  defaultOfferQty = 25,
  discussedOfferQty = 5,
  newOfferQty = 5,
}
